### ISSUE TITLE
Lots of Methods Aren't Async

### ISSUE THREAD

**Issue by rdegges** [okta/okta-sdk-nodejs#79] opened 2018-10-11 14:05 UTC
It would be great if we could mark a lot of the core SDK methods as `async` functions so you can use async/await patterns more easily.

A common use case, for example, is iterating through org users and doing something with each user. For instance:

```javascript
client.listUsers().each(user => {
  // code here
  await someAsyncFunctionIWrote(); // <--- this always fails since .each() isn't async :(
});
```

If we make the iterators proper async functions it allows developers to use cleaner development practices in a lot of places. What do y'all think?

**Comment by kevlened** [comment] 2018-12-03 17:42
The `each` method handles async callbacks, but the `async` keyword is missing from your example.

```javascript
client.listUsers().each(async user => {
  await someAsyncFunctionIWrote();
});
```

**Comment by kevlened** [comment] 2018-12-03 18:03
If #82 gets in, this can be even cleaner on newer versions of Node:

Before:
```javascript
async function someMethod() {
  await client.listUsers().each(async user => {
    await someAsyncFunctionIWrote();
  });
  console.log('listed all users');
}
```

After:
```javascript
async function someMethod() {
  for await (let user of client.listUsers()) {
    console.log(user);
  }
  console.log('listed all users');
}
```

**Comment by fas3r** [comment] 2019-03-03 00:58
Hello @kevlened , 

Any news regarding [#82](https://github.com/okta/okta-sdk-nodejs/pull/82) ? 

thanks by advance

**Comment by kevlened** [comment] 2019-03-03 23:24
@fas3r Thanks for your interest! It looks like @swiftone maintains the repo now and I'm not sure how the roadmap/timeline looks.

**Comment by fas3r** [comment] 2019-03-04 00:19
Hello @kevlened ,

It's fine, I wrap the call that I needed using the HTTP API, it's easier as all call are async with axios.

Thanks anyway for your answer.

**Comment by kevlened** [comment] 2019-03-04 18:48
@fas3r No changes are need to use `async/await` with the SDK today (the issue is misleading)! Anything that returns a Promise is compatible with `async/await` and every published version of the SDK returns Promises for each call.

My change simply enables the new `async` iteration syntax when looping through a list, but you can get basically the same usage with the `each` function I showed before:

```javascript
await client.listUsers().each(async user => {
    await someAsyncFunction();
});
```

**Comment by oleksandrpravosudko-okta** [comment] 2021-11-10 11:32
Closing this as `Client` methods and `Collection` iterator can be used with `async/await`.

**Closed by oleksandrpravosudko-okta** 2021-11-10 11:32 UTC
