### ISSUE TITLE
node-gyp error

### ISSUE THREAD

**Issue by ror6ax** [okta/okta-sdk-nodejs#104] opened 2019-05-13 12:50 UTC
Node v12.1.0

> npm install @okta/okta-sdk-nodejs --save gives me following output:

```
/Users/g.reshetniak/.node-gyp/12.1.0/include/node/v8.h:2544:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                    Local<String> ToString(Isolate* isolate) const);
                                  ^
../core.cc:97:19: warning: 'Call' is deprecated [-Wdeprecated-declarations]
        callback->Call(0, NULL);
                  ^
../../nan/nan.h:1673:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:103:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../core.cc:107:36: error: too few arguments to function call, single argument 'context' was not specified
    int mask = info[0]->Int32Value();
               ~~~~~~~~~~~~~~~~~~~ ^
/Users/g.reshetniak/.node-gyp/12.1.0/include/node/v8.h:2569:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/g.reshetniak/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
2 warnings and 9 errors generated.
make: *** [Release/obj.target/core/core.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/g.reshetniak/okta-activator/node_modules/modern-syslog
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@1.1.4 (node_modules/modern-syslog):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@1.1.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ @okta/okta-sdk-nodejs@2.0.0
updated 1 package in 12.544s
```

Not sure what is causing this, please advice. 

Thanks.

**Comment by swiftone** [comment] 2019-05-22 21:24
Hi @ror6ax - Thanks for the report.  While we look into the issue, have you tried the following:
* clear out your `node_modules/` directory and run `npm install` to replace any binaries from older node versions
* If that doesn't work, does this issue appear on older node versions?

**Comment by rdegges** [comment] 2020-10-02 18:57
Hey all! I cannot reproduce this in the latest version of this library. I propose closing this out.

**Closed** 2020-10-02 18:59 UTC
Labels: bug, requires-reproduce
